//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHUTUNG
    {
        public int MaPhieu { get; set; }
        public int MaPT { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PHIEUSUACHUA PHIEUSUACHUA { get; set; }
        public virtual PHUTUNG PHUTUNG { get; set; }
    }
}
