//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public DICHVU()
        {
            this.CT_DICHVU = new HashSet<CT_DICHVU>();
        }
    
        public int MaDV { get; set; }
        public string TenDV { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual ICollection<CT_DICHVU> CT_DICHVU { get; set; }
    }
}
