//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageManagementEntities : DbContext
    {
        public GarageManagementEntities()
            : base("name=GarageManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_DICHVU> CT_DICHVU { get; set; }
        public DbSet<CT_PHUTUNG> CT_PHUTUNG { get; set; }
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHIEUSUACHUA> PHIEUSUACHUAs { get; set; }
        public DbSet<PHUTUNG> PHUTUNGs { get; set; }
        public DbSet<XE> XEs { get; set; }
    }
}
