//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUSUACHUA
    {
        public PHIEUSUACHUA()
        {
            this.CT_DICHVU = new HashSet<CT_DICHVU>();
            this.CT_PHUTUNG = new HashSet<CT_PHUTUNG>();
        }
    
        public int MaPhieu { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ICollection<CT_DICHVU> CT_DICHVU { get; set; }
        public virtual ICollection<CT_PHUTUNG> CT_PHUTUNG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
