//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTUNG
    {
        public PHUTUNG()
        {
            this.CT_PHUTUNG = new HashSet<CT_PHUTUNG>();
        }
    
        public int MaPT { get; set; }
        public string TenPT { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
    
        public virtual ICollection<CT_PHUTUNG> CT_PHUTUNG { get; set; }
    }
}
