//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GarageManagement.Enities
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        public XE()
        {
            this.PHIEUSUACHUAs = new HashSet<PHIEUSUACHUA>();
        }
    
        public int MaXe { get; set; }
        public string BienSo { get; set; }
        public string TenXe { get; set; }
        public string HangXe { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<PHIEUSUACHUA> PHIEUSUACHUAs { get; set; }
    }
}
